language: node_js

node_js:
- '12'

install:
- TMPDIR=/tmp yarn install

script:
- yarn $TEST_SUITE

cache: false

addons:
  chrome: stable
  firefox: latest

env:
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=test
  - TEST_SUITE=test:testcafe-ci
  - TEST_SUITE=commitlint-travis
